### ISSUE TITLE
[Ansible] Add ntp install to the common role

### ISSUE THREAD

**Issue by anatolek** [Kv-126-DevOps/ansible#2]
TODO list

- install and configure NTP service
- add timezone configuration

---

Add `common/ntp.yaml` and update `common/main.yaml` with the following lines:

```yaml
- import_tasks: ntp.yaml
  tags:
    - never
    - common_install
    - common_ntp_install
```
