### ISSUE TITLE
[Ansible] Add utilities install to the common role

### ISSUE THREAD

**Issue by anatolek** [Kv-126-DevOps/ansible#3]
TODO list

- install some necessary utilities if they are not installed
  - 'bind-utils'
  - 'curl'
  - 'htop'
  - 'iotop'
  - 'atop'
  - 'iftop'
  - 'ncdu'
  - 'net-tools'
  - 'tmux'
  - 'telnet'
  - 'vim'
  - 'wget'
  - 'mc'
  - 'nmap'
  - 'ca-certificates'
  - 'lsof'

You can add (or remove) other utilities if you see fit.

---

Add `common/utilities.yaml` and update `common/main.yaml` with the following lines:

```yaml
- import_tasks: utilities.yaml
  tags:
    - never
    - common_install
    - common_utilities_install
```
