### ISSUE TITLE
[Ansible] Add SSH configuration to common role

### ISSUE THREAD

**Issue by anatolek** [Kv-126-DevOps/ansible#4]
TODO list

- configure SSH
  - `/etc/ssh/sshd_config` (SSH daemon config)
  - `/etc/ssh/ssh_config` (SSH client config)

Make all the necessary settings as you see fit

---

Add `common/ssh.yaml` and update `common/main.yaml` with the following lines:

```yaml
- import_tasks: ssh.yaml
  tags:
    - never
    - common_install
    - common_ssh_install
```
