### ISSUE TITLE
[Ansible] Add sysctl configuration to the common role

### ISSUE THREAD

**Issue by anatolek** [Kv-126-DevOps/ansible#5]
TODO list

- add all necessary sysctl configuration to the common role

---

Add `common/sysctl.yaml` and update `common/main.yaml` with the following lines:

```yaml
- import_tasks: sysctl.yaml
  tags:
    - never
    - common_install
    - common_sysctl_configure
```
