### ISSUE TITLE
[Ansible] Add login.defs configuration to the common role

### ISSUE THREAD

**Issue by anatolek** [Kv-126-DevOps/ansible#6]
TODO list

- configure `/etc/login.defs`

Make all the necessary settings as you see fit

---

Add `common/account_settings.yaml` and update `common/main.yaml` with the following lines:

```yaml
- import_tasks: account_settings.yaml
  tags:
    - never
    - common_install
    - common_account_configure
```
