### ISSUE TITLE
[Ansible] Add banner configuration to the common role

### ISSUE THREAD

**Issue by anatolek** [Kv-126-DevOps/ansible#7]
TODO list

- configure `/etc/motd`
- configure `/etc/issue[.net]` if you want

Make all the necessary settings as you see fit

Example: https://github.com/blackbaud/ansible-role-linux-hardening/blob/master/templates/common-motd.j2

---

Add `common/banner.yaml` and update `common/main.yaml` with the following lines:

```yaml
- import_tasks: banner.yaml
  tags:
    - never
    - common_install
    - common_banner_configure
```
